name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # First job: Submodules at their current commit
  build-current-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch submodules at their current commit

      - name: configure
        run: ./configure

      - name: make
        run: make

      - name: make check
        run: make check

      - name: make distcheck
        run: make distcheck

  # Second job: Submodules on their latest master branch
  build-latest-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch submodules at their current commit initially

      - name: Checkout latest master for submodules
        run: |
          git submodule foreach 'git checkout master && git pull origin master'

      - name: configure
        run: ./configure

      - name: make
        run: make

      - name: make check
        run: make check

      - name: make distcheck
        run: make distcheck
